### ISSUE TITLE
Selecting a Mule platform when detected a mule configuration file hangs.

### ISSUE THREAD

**Issue by phiroict** [machaval/mule-intellij-plugins#37]
Hi Machaval, first, thanks for your plugin, it gives me a reason to avoid that dreadful eclipse. 

Now for the issue: 

How to reproduce: 
- Open a mule project -> you get the "Frameworks detected" Mule Framework framework (sic) is detected in the project. Configure.
- Click on Configure.
- Selected the properties and select Ok
- You now get the "Add Mule Framework support" since there are none defined we create one: 
- Press create
- In the "Select Folder for the new Mule SDK" the "+"
- Now a Mule SDK screen is shown where you can select / drop the distribution folder: Issue us that on the right side under the "recent files" drop down a "waiting twirly" animation that does not stop. You cannot select folders and cannot drop folders on the file pane. (or anywhere else) canceling is the only thing to do. 

Info: IntelliJ 2016.2.1 - Linux Ubuntu 16.04 (64) [Runs as a virtualbox VM under windows 7 ]- JDK 8_0_92 

I could not find any relevant log files.

**Comment by machaval** [comment]
Thanks philip for the report  of the issue will try to fix it for next
release

**Comment by machaval** [comment]
Hi I'm not able to reproduce this issue can you put a screenshot. And a threaddump. That editor is a estandar intellij widget.

**Comment by phiroict** [comment]
I begin to believe it was a conflict within the installation, I reinstalled from scratch (IDEA) and the issue disappeared.
