### ISSUE TITLE
flow-ref with MEL expression is highlighted as error

### ISSUE THREAD

**Issue by javaduke** [machaval/mule-intellij-plugins#38]
See the screenshot. MEL expressions in flow-ref are accepted, but the editor does not like it.
![screen shot 2016-08-05 at 9 00 18 am](https://cloud.githubusercontent.com/assets/561559/17442612/59efe994-5aeb-11e6-8405-0f78cab68b52.png)

**Comment by machaval** [comment]
Fixed on next release
