### ISSUE TITLE
PhpStrom

### ISSUE THREAD

**Issue by iwex** [machaval/mule-intellij-plugins#47]
Hello! Still no Raml support in PhpStorm..

**Comment by machaval** [comment]
That is weird since i tried to install it from disk and it did work let me
try it from repo and I will back to you

**Comment by machaval** [comment]
I was able to install it from repo 
![screenshot from 2016-10-03 11 48 35](https://cloud.githubusercontent.com/assets/101496/19041694/650a8404-895f-11e6-977a-1d66a681c8d2.png)

Please make sure you are using the latest PhpStorm

**Comment by iwex** [comment]
Yeah, but it doesn't work
![screenshot at 2016-10-03 18-18-48](https://cloud.githubusercontent.com/assets/4510068/19042741/d977ff48-8995-11e6-84b8-fc07327db313.png)
![screenshot at 2016-10-03 18-20-33](https://cloud.githubusercontent.com/assets/4510068/19042790/1accdd74-8996-11e6-85db-578789e7e05f.png)

**Comment by machaval** [comment]
I see will take a look at it. Don't know why it doesn't recognize the
plugin.

**Comment by MatthewHartstonge** [comment]
I think the issue is that RAML is not being loaded under 'Settings > Editor > File Types', hence no highlighting. 
I'm using it with both WebStorm + PyCharm, same issue.

**Comment by christophlingg** [comment]
same here with pycharm

**Comment by ropsiu** [comment]
Same for PhpStorm 2016.2. Is there a possibility to add raml filetype in File Types settings to work with this plugin? Screenshot anyone?

**Comment by jotes** [comment]
Support for PyCharm (and probably for phpstorm) should be enabled when https://github.com/machaval/mule-intellij-plugins/pull/68 will land in the plugins repository.

**Comment by jotes** [comment]
@machaval Hi, do you have an estimation when #68 will land in The Jetbrains plugins repository? I can try to help if there are any problems.

**Comment by machaval** [comment]
This was released on latest version
