### ISSUE TITLE
filter selector is not recognized

### ISSUE THREAD

**Issue by jeffbowman** [machaval/mule-intellij-plugins#74]
input: 
```
{
    "responses": [
        {
            "question": "First Name",
            "answer": "Clark"
        }, {
            "question": "Last Name",
            "answer": "Kent"
        }
    ]
}
```
weave:
``` 
%dw 1.0
%output application/java
---
{
    firstName: payload.responses[?($.question == "First Name")][0].answer,
    lastName: payload.responses[?($.question == "Last Name")][0].answer
}
```
the `[?($.question == ...)]` gives an error at the `?`, however, this is valid weave syntax and passes unit tests and works in Anypoint Studio as written.

The error is: 

>` ',', <expression>, <selector>, <value expression>, ']' or '}' expected, got '?'`

Relevant Mulesoft documentation is in the `Selectors` section under the [Key Present](https://docs.mulesoft.com/mule-user-guide/v/3.8/dataweave-selectors#key-present) heading.  You'll have to scroll down to the third example, which follows this text 

> You can also use this validation operation as part of a filter:

My install configuration:
IntelliJ IDEA CE 2016.3.4
Build IC-163.12024.16
Plugin version 0.8
Oracle JDK 1.8.0_112-release-408.b6 x86_64

**Comment by javaduke** [comment]
Resolved in 0.9
