### ISSUE TITLE
Support MUnit and APIKit

### ISSUE THREAD

**Issue by javaduke** [machaval/mule-intellij-plugins#8]
I know it's a very long shot but it would be nice to have APIKit and MUnit support :) I'm sure at least some of it can be done using Maven archetypes, I will do some research on it tomorrow.

**Comment by machaval** [comment]
From apikit we should look at the scaffolder api that should no be very hard to do. MUnit is not that simple we need a runner. This should be two separate tasks

**Comment by javaduke** [comment]
Since the projects are Maven based, IMHO runner is not necessary, I can just use munit:test goal.
