### ISSUE TITLE
Incorrect maven configuration loaded when multiple Mule modules in same IntelliJ project

### ISSUE THREAD

**Issue by davidwiking** [machaval/mule-intellij-plugins#80]
If one have multiple Mule modules in the same project the run configuration fails if the module is not named as the value of maven name property. Since IDEA naming defaults to artifactId when importing a maven project as a module the mapping functionality should be fixed to check module-name vs maven artifactId.
Or if possible, use the configured module to extract maven configuration.

**Comment by davidwiking** [comment]
Looked into the code a bit more and found a better solution than the name comparison.

**Comment by javaduke** [comment]
PR merged, will release this weekend
