### ISSUE TITLE
The doc namespace is not recognized

### ISSUE THREAD

**Issue by jbenhamou** [machaval/mule-intellij-plugins#91]
By default the doc namespace is not recognized. IntelliJ shows this declaration in red: `xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"`

**Comment by javaduke** [comment]
OK, that I can tell you right now - NO, it is not going to happen. Ever. The `doc` namespace has no right to exist. It is only used by Studio, and would you agree, an XML attribute is a wrong place to add comments/docs/whatever is not required to execute the code.
