### ISSUE TITLE
Specify a "main" RAML file for IntelliJ RAML plugin?

### ISSUE THREAD

**Issue by adjokic** [machaval/mule-intellij-plugins#93]
Hello,
I have my main api.raml file which contains all of the essentials:
```
#%RAML 1.0
title: My API
[...]
uses:
[...]
types:
[...]
/endpoint:
  get:
    response:
[...]
```
In order to simplify this file, I externalized all libraries and types, so for example, I have:
```
types:
  user: !include user.raml
  userType: !include userType.raml
```
Now if we want to reference the userType inside the user.raml, IntelliJ says it cannot find the reference. However, if I start up the RAML API console, the type is resolved and everything is displayed nicely.
I want to avoid having to do the following inside user.raml
```
#%RAML 1.0 DataType
[...]
properties:
  type: !include userType.raml
```
Is there a way to get the plugin to recognize/resolve all types defined in my main api.raml file and reuse these inside other .raml files?

**Comment by javaduke** [comment]
Could you please attach your project to the case? There are several different ways to externalize types in RAML. You can create a #%RAML 1.0 Library, define your types there, and then in your API you can have:

```
uses:
  myApiTypes: types.raml 
```

and then refer to a particular type as, e.g. myApiTypes.CustomerType. This works fine in IntelliJ.
I'm not saying your method is wrong, just suggesting an alternative.

**Comment by adjokic** [comment]
Hi,

I've simplified some of the RAML to try and point out the main issues I want to address, along with what I am trying to represent. (I had to rename all files to .txt):
[api.raml.txt](https://github.com/machaval/mule-intellij-plugins/files/1044684/api.raml.txt)

**types:**
[document.raml.txt](https://github.com/machaval/mule-intellij-plugins/files/1044688/document.raml.txt)
[documentType.raml.txt](https://github.com/machaval/mule-intellij-plugins/files/1044689/documentType.raml.txt)
[error.raml.txt](https://github.com/machaval/mule-intellij-plugins/files/1044678/error.raml.txt)
[group.raml.txt](https://github.com/machaval/mule-intellij-plugins/files/1044692/group.raml.txt)
[user.raml.txt](https://github.com/machaval/mule-intellij-plugins/files/1044694/user.raml.txt)

**libraries:**
[DocumentsLibrary.raml.txt](https://github.com/machaval/mule-intellij-plugins/files/1044680/DocumentsLibrary.raml.txt)

**traits:**
[400-error.raml.txt](https://github.com/machaval/mule-intellij-plugins/files/1044685/400-error.raml.txt)
[404-error.raml.txt](https://github.com/machaval/mule-intellij-plugins/files/1044686/404-error.raml.txt)


I have gone down the road of trying to put things in libraries, but this doesn't scale after some point either, because everything will end up in one file again.

In the examples with the traits, I had to !include the error type, because if I just put "error", the IntelliJ plugin tells me that the type cannot be resolved. However, the RAML API Console, for example, has no issue resolving the error type, and displays this properly.

I am giving the example of the DocumentsLibrary to show how I have circumvented the issue of using multiple types (in this case a union) within another object type. One issue here, however, is that I won't be able to reuse any types defined in the DocumentsLibrary for the purposes of inheritance or composition, for example. Another issue with using a library is that I have to sometimes define a data type twice, in this case document and group.

One could just access DocumentsLibrary.document from the main api.raml, but let's say that we have a FolderLibrary, for example, which also requires the document type. Now I have multiple libraries to choose the same object from.
One consequence is that somebody reading the API Console might get confused because of the seemingly different types. Another consequence is that a code generator might end up producing two different types called DocumentsLibraryDocument and FolderLibraryDocument.

Please let me know if this makes sense. I do hope that the attached raml files can provide more insight and are worth more than the above 229 words.

Thank you
