### ISSUE TITLE
"Invalid Element" error when defining type in included collection response

### ISSUE THREAD

**Issue by whampop** [machaval/mule-intellij-plugins#94]
When including a resourceType, I'm getting a parsing error "Invalid Element: {type: %value%}" in the ResourceType's .raml, I've tried custom and built in data types with the same result: 

![image](https://cloud.githubusercontent.com/assets/1829001/26740520/8b5b1b32-479b-11e7-810f-bed9abab6885.png)

I found this issue in the [raml-java-parser #337 ](https://github.com/raml-org/raml-java-parser/issues/337) which seems to have been fixed a version ago (1.0.8), but I am unsure how to check the version in this plugin uses (assuming it uses raml-java-parser). I'm thinking it is not at latest version? 

Thank you, and thanks for the great plugin.

**Comment by whampop** [comment]
![image](https://cloud.githubusercontent.com/assets/1829001/26740860/dca82164-479c-11e7-8305-087a9c3a3fd2.png)

**Comment by javaduke** [comment]
RAML parser updated to 1.0.10 - #89
