### ISSUE TITLE
FeatureRequest - Allow runtimes prior to 3.7

### ISSUE THREAD

**Issue by jeffbowman** [machaval/mule-intellij-plugins#96]
I work for clients, some of whom are still on Mule 3.5. I would like to be able to use these plugins while developing for them (especially to run in debug mode or in standalone mode for demos) but these plugins only allow runtimes from 3.7. I realize DataWeave is not available before 3.7, but there is still value in using this tool for development on legacy runtimes. This becomes more true as we work toward migrating from 3.5 to 3.8, as it means I can test with 3.5 and 3.8 by simply changing the runtime while staying in IntelliJ. 

Appreciate the work on these plugins, IntelliJ is a my preferred development platform, I try to dodge using Eclipse and Eclipse based products as much as possible. This tool is much higher quality in my opinion, so thanks for writing it!

**Comment by javaduke** [comment]
Sorry, Jeff, I'm not sure how much I need to invest in it, given the fact that 3.5 is a really old one. I may consider this, but not any time soon, there are more important things to address.
